import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'hope-e2e-'));
if (!process.env.DATABASE_URL) process.env.DATA_FILE = path.join(tmp, 'hope.json');
process.env.STORAGE_DIR = path.join(tmp, 'storage');
process.env.NODE_ENV = 'test';
const { createServer } = await import('../src/app.js');
const { db } = await import('../src/db.js');
const server = createServer();
await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}/api/v1`;
const json = (url, options={}) => fetch(base+url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}).then(async r=>({status:r.status,body:await r.json()}));
let alice,bob,job,offer;
test('full marketplace flow', async () => {
  let r=await json('/auth/register',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'pass12345',displayName:'Owner'})}); assert.equal(r.status,201); alice=r.body.data;
  r=await json('/auth/register',{method:'POST',body:JSON.stringify({email:'provider@example.com',password:'pass12345',displayName:'Provider'})}); assert.equal(r.status,201); bob=r.body.data;
  r=await json('/categories'); assert.equal(r.status,200); const category=r.body.data[0].id;
  r=await json('/jobs',{method:'POST',headers:{Authorization:`Bearer ${alice.accessToken}`},body:JSON.stringify({title:'Test job',description:'Do it',categoryId:category,jobType:'FIXED',budgetType:'FIXED',budgetMin:100,budgetMax:150,duration:3,acceptanceCriteria:'done'})}); assert.equal(r.status,201); job=r.body.data;
  r=await json(`/jobs/${job.id}/publish`,{method:'POST',headers:{Authorization:`Bearer ${alice.accessToken}`}}); assert.equal(r.status,200);
  r=await json('/offers',{method:'POST',headers:{Authorization:`Bearer ${bob.accessToken}`},body:JSON.stringify({jobId:job.id,price:120,message:'yes'})}); assert.equal(r.status,201); offer=r.body.data;
  r=await json(`/offers/${offer.id}/accept`,{method:'POST',headers:{Authorization:`Bearer ${alice.accessToken}`}}); assert.equal(r.status,200);
  r=await json(`/payments/fund/${job.id}`,{method:'POST',headers:{Authorization:`Bearer ${alice.accessToken}`,'Idempotency-Key':'e2e-1'},body:'{}'}); assert.equal(r.status,201); const firstPayment=r.body.data;
  r=await json(`/payments/fund/${job.id}`,{method:'POST',headers:{Authorization:`Bearer ${alice.accessToken}`,'Idempotency-Key':'e2e-1'},body:'{}'}); assert.equal(r.status,200); assert.equal(r.body.data.id,firstPayment.id);
  r=await json(`/jobs/${job.id}/start`,{method:'POST',headers:{Authorization:`Bearer ${bob.accessToken}`}}); assert.equal(r.status,200);
  r=await json(`/jobs/${job.id}/evidence`,{method:'POST',headers:{Authorization:`Bearer ${bob.accessToken}`},body:JSON.stringify({uri:'https://example.com/evidence'})}); assert.equal(r.status,201);
  r=await json(`/jobs/${job.id}/deliver`,{method:'POST',headers:{Authorization:`Bearer ${bob.accessToken}`}}); assert.equal(r.status,200);
  r=await json(`/jobs/${job.id}/accept`,{method:'POST',headers:{Authorization:`Bearer ${alice.accessToken}`}}); assert.equal(r.status,200);
  r=await json(`/payments/release/${job.id}`,{method:'POST',headers:{Authorization:`Bearer ${alice.accessToken}`}}); assert.equal(r.status,200); assert.equal(r.body.data.status,'RELEASED');
});
after(async ()=>{ await db.close(); await new Promise(r=>server.close(r)); fs.rmSync(tmp,{recursive:true,force:true}); });
